# Generated by Django 3.2 on 2021-05-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Fuera de plazo', 'Fuera de plazo'), ('Activo', 'Activo')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Job', models.CharField(max_length=200, null=True)),
                ('payment', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Practica', 'Practica'), ('Part-Time', 'Part-Time'), ('Full-Time', 'Full-Time')], max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
