# Generated by Django 3.2 on 2021-05-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_estado_trabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=200, null=True)),
                ('heading', models.CharField(choices=[('Informatica', 'Informatica'), ('Medicina', 'Medicina'), ('Administracion', 'Administracion'), ('Mecanico', 'Mecanico'), ('Otro', 'Otro')], max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
