# Generated by Django 3.2 on 2021-05-01 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210501_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.empresa'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
